# Generated by Django 5.1.3 on 2024-11-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
