# Generated by Django 5.1.3 on 2024-11-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productoapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
