# Generated by Django 5.1.3 on 2024-11-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoapi', '0002_remove_producto_precio_producto_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='price',
            new_name='precio',
        ),
    ]
